In [1]:
import numpy as np

In [2]:
# Dimensions of the matrix:
rows = 7
cols = 4
depth = 5

In [7]:
# Creating the matrices:
A = np.zeros((rows,cols))
print(A.shape)

(7, 4)


In [8]:
A = np.zeros((depth, rows, cols))

In [10]:
A = np.ones((rows, cols))

In [49]:
A = np.array([(1,2,3), (4,5,6), (7,8,9)])
d = np.diag(A)
d = np.diag(d)

In [48]:
d

array([1, 5, 9])

In [46]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
print (1.0/A)

[[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]
 [0.14285714 0.125      0.11111111]]


In [18]:
a = np.array((1,2,3))

In [20]:
a.shape

(3,)

In [21]:
print(a.reshape(-1,1).shape)

(3, 1)


In [27]:
print(a.reshape(1,-1).shape)

(1, 3)


In [29]:
print(a.reshape(1,-1).reshape(-1).shape)

(3,)


In [39]:
X = np.array([(1,2,3), (4,5,6), (7,8,9)])
print(X)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [43]:
X = np.array([(1,2,3), (4,5,6), (7,8,9)])
u = np.array((1,2,3))
for i_row in range(0, X.shape[0]):
    X[i_row,:]= X[i_row,:] - u
print(X)

[[0 0 0]
 [3 3 3]
 [6 6 6]]


In [40]:
print(u)

[1 2 3]


In [42]:
X = np.array([(1,2,3),(4,5,6),(7,8,9)])
u = np.array((1,2,3))
for i_row in range(0,X.shape[0]):
    X[i_row,:] = X[i_row,:] - u
print(X)

[[0 0 0]
 [3 3 3]
 [6 6 6]]


In [44]:
X = np.array([(1,2,3),(4,5,6),(7,8,9)])
u = np.array((1,2,3))
X = X - u
print(X)

[[0 0 0]
 [3 3 3]
 [6 6 6]]
